# Generated by Django 3.1.4 on 2020-12-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201223_0019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
