# Generated by Django 3.1.4 on 2020-12-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
    ]
